3.4 updates
ulsdevteam/inlineHtmlGalley pull request #13
Opened 2024-09-17 14:43 UTC by trp89

2024-10-28 19:35 UTC, trp89 commented
@ctgraham and/or @wopsononock I just wanted another quick onceover to make sure these are good to merge the pull request

2024-12-18 14:57 UTC, ctgraham requested changes
For PHP files, PKP has standardized to spaces rather than tabs, so we should keep that convention when possible.

Note that the bootstrap3 templates use tabs rather than spaces, so using tabs in the templates here is acceptable.

2024-12-18 14:57 UTC, ctgraham commented on InlineHtmlGalleySettingsForm.php
> +	/** @var $plugin InlineHtmlGalleyPlugin */
This file was committed with tabs, but PKP has standardized on spaces.

2024-12-18 14:57 UTC, ctgraham commented on InlineHtmlGalleySidebarBlockPlugin.php
> +	abstract function blockName();
Spaces in this file were changed to tabs, but PKP has standardized on spaces.

2024-12-19 20:22 UTC, merged